### ISSUE TITLE
Plugin not load

### ISSUE THREAD

**Issue by TiTo-418** [savethewools/Authenticator#1]
Logs: http://pastebin.com/zrPAGCws

**Comment by TiTo-418** [comment]
@iEli2tyree011 @dentmaged

**Comment by iEli2tyree011** [comment]
@TiTo-418 How are you compiling the plugin?

**Comment by TiTo-418** [comment]
@iEli2tyree011 Yes

**Comment by iEli2tyree011** [comment]
The pom.xml doesn't have the required libraries to export when building

**Comment by TiTo-418** [comment]
Fixed https://github.com/savethewools/Authenticator/pull/2
